In [45]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import scatter_matrix
%matplotlib inline
from matplotlib.ticker import StrMethodFormatter

In [46]:
pip install Keras

Note: you may need to restart the kernel to use updated packages.


In [47]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [48]:
df = pd.read_csv("health care diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [49]:
X = df.iloc[:, 0:8].values
y = df.iloc[:, 8].values

In [50]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [51]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [53]:
X_test.shape

(231, 8)

In [54]:
y_train.shape

(537,)

In [55]:
y_test.shape

(231,)

In [56]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [57]:
conda install tensorflow

Solving environment: ...working... done

# All requested packages already installed.

Note: you may need to restart the kernel to use updated packages.



In [58]:
import tensorflow as tf

In [59]:
pip install --upgrade tensorflow


Note: you may need to restart the kernel to use updated packages.


In [60]:
pip install --upgrade tensorflow-gpu

Note: you may need to restart the kernel to use updated packages.


In [61]:
#Importing Keras & classes
from tensorflow import keras

In [62]:
from tensorflow.keras import datasets, layers, models, optimizers
from tensorflow.keras.preprocessing import image


In [63]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [64]:
from tensorflow.keras.preprocessing import image_dataset_from_directory


In [65]:
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from tensorflow.keras import layers, models, optimizers
import tensorflow.keras.backend as K

In [66]:
from tensorflow.keras.callbacks import Callback, ModelCheckpoint, ReduceLROnPlateau, EarlyStopping

In [67]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense

In [68]:
#Initializing the Artificial Neural Network
classifier = tf.keras.Sequential()

In [69]:
#Adding the input layer and a hidden layer
classifier.add(Dense(5, input_dim=8, activation='relu'))

In [70]:
#Adding the second hidden layer
classifier.add(Dense(5, activation='relu'))

In [71]:
 #Adding output layer
classifier.add(Dense(1, activation='sigmoid'))

In [72]:
#Compiling the artificial neural network
classifier.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [73]:
# Fitting the ANN model to the training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 150)

Epoch 1/150
54/54 [==============================] - 1s 1ms/step - loss: 0.7640 - accuracy: 0.4339
Epoch 2/150
54/54 [==============================] - 0s 1ms/step - loss: 0.7197 - accuracy: 0.5531
Epoch 3/150
54/54 [==============================] - 0s 2ms/step - loss: 0.6948 - accuracy: 0.6201
Epoch 4/150
54/54 [==============================] - 0s 1ms/step - loss: 0.6756 - accuracy: 0.6257
Epoch 5/150
54/54 [==============================] - 0s 2ms/step - loss: 0.6564 - accuracy: 0.6443
Epoch 6/150
54/54 [==============================] - 0s 2ms/step - loss: 0.6375 - accuracy: 0.6629
Epoch 7/150
54/54 [==============================] - 0s 2ms/step - loss: 0.6184 - accuracy: 0.6797
Epoch 8/150
54/54 [==============================] - 0s 2ms/step - loss: 0.5983 - accuracy: 0.6927
Epoch 9/150
54/54 [==============================] - 0s 1ms/step - loss: 0.5794 - accuracy: 0.7076
Epoch 10/150
54/54 [==============================] - 0s 2ms/step - loss: 0.5616 - accuracy: 0.7151
Epoch 11/

54/54 [==============================] - 0s 1ms/step - loss: 0.4518 - accuracy: 0.7672
Epoch 84/150
54/54 [==============================] - 0s 1ms/step - loss: 0.4517 - accuracy: 0.7691
Epoch 85/150
54/54 [==============================] - 0s 1ms/step - loss: 0.4514 - accuracy: 0.7691
Epoch 86/150
54/54 [==============================] - 0s 2ms/step - loss: 0.4510 - accuracy: 0.7672
Epoch 87/150
54/54 [==============================] - 0s 2ms/step - loss: 0.4507 - accuracy: 0.7691
Epoch 88/150
54/54 [==============================] - 0s 1ms/step - loss: 0.4506 - accuracy: 0.7821
Epoch 89/150
54/54 [==============================] - 0s 1ms/step - loss: 0.4497 - accuracy: 0.7728
Epoch 90/150
54/54 [==============================] - 0s 1ms/step - loss: 0.4492 - accuracy: 0.7728
Epoch 91/150
54/54 [==============================] - 0s 1ms/step - loss: 0.4485 - accuracy: 0.7747
Epoch 92/150
54/54 [==============================] - 0s 1ms/step - loss: 0.4480 - accuracy: 0.7728
Epoch 93/150


In [74]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred[:10]

array([[0.99252015],
       [0.05512094],
       [0.03146517],
       [0.55441684],
       [0.1292524 ],
       [0.01606256],
       [0.79747677],
       [0.6532572 ],
       [0.46133825],
       [0.46477622]], dtype=float32)

In [75]:
#Converting probabilities into a binary result
y_pred = (y_pred > 0.5)
y_pred[:10]

array([[ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False]])

In [76]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[138,  19],
       [ 33,  41]], dtype=int64)

In [77]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       157
           1       0.68      0.55      0.61        74

    accuracy                           0.77       231
   macro avg       0.75      0.72      0.73       231
weighted avg       0.77      0.77      0.77       231



In [ ]:
#Accuracy is 77%